// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BasketProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ro.Mpp2024.Protocol {

  /// <summary>Holder for reflection information generated from BasketProtocol_v3.proto</summary>
  public static partial class BasketProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for BasketProtocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BasketProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdCYXNrZXRQcm90b2NvbF92My5wcm90bxITcm8ubXBwMjAyNC5wcm90b2Nv",
            "bCI7CgVCaWxldBIMCgRtZWNpGAEgASgFEhIKCm51bWVDbGllbnQYAiABKAkS",
            "EAoIbnJMb2N1cmkYAyABKAUiNAoETWVjaRIMCgRudW1lGAEgASgJEhAKCG5y",
            "TG9jdXJpGAIgASgFEgwKBHByZXQYAyABKAIiLAoIUGVyc29hbmESEAoIdXNl",
            "cm5hbWUYASABKAkSDgoGcGFyb2xhGAIgASgJIrgCCg1CYXNrZXRSZXF1ZXN0",
            "EjUKBHR5cGUYASABKA4yJy5yby5tcHAyMDI0LnByb3RvY29sLkJhc2tldFJl",
            "cXVlc3QuVHlwZRIrCgViaWxldBgCIAEoCzIaLnJvLm1wcDIwMjQucHJvdG9j",
            "b2wuQmlsZXRIABIpCgRtZWNpGAMgASgLMhkucm8ubXBwMjAyNC5wcm90b2Nv",
            "bC5NZWNpSAASMQoIcGVyc29hbmEYBCABKAsyHS5yby5tcHAyMDI0LnByb3Rv",
            "Y29sLlBlcnNvYW5hSAAiWgoEVHlwZRILCgdVbmtub3duEAASCQoFTG9naW4Q",
            "ARIKCgZMb2dvdXQQAhIOCgpWaW5kZUJpbGV0EAMSCgoGR2V0QWxsEAQSEgoO",
            "R2V0RGlzcG9uaWJpbGUQBUIJCgdwYXlsb2FkItUCCg5CYXNrZXRSZXNwb25z",
            "ZRI2CgR0eXBlGAEgASgOMigucm8ubXBwMjAyNC5wcm90b2NvbC5CYXNrZXRS",
            "ZXNwb25zZS5UeXBlEg0KBWVycm9yGAIgASgJEi8KCHBlcnNvYW5hGAMgASgL",
            "Mh0ucm8ubXBwMjAyNC5wcm90b2NvbC5QZXJzb2FuYRIpCgViaWxldBgEIAEo",
            "CzIaLnJvLm1wcDIwMjQucHJvdG9jb2wuQmlsZXQSKgoHbWVjaXVyaRgFIAMo",
            "CzIZLnJvLm1wcDIwMjQucHJvdG9jb2wuTWVjaSJ0CgRUeXBlEgsKB1Vua25v",
            "d24QABIGCgJPaxABEgkKBUVycm9yEAISDAoITG9nZ2VkaW4QAxINCglMb2dn",
            "ZWRvdXQQBBIPCgtCaWxldFZhbmR1dBAFEgoKBkdldEFsbBAGEhIKDkdldERp",
            "c3BvbmliaWxlEAdCLwobcm8ubmV0d29yay5wcm90b2J1ZlByb3RvY29sQhBC",
            "YXNrZXRQcm90b2J1ZmZzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protocol.Bilet), global::Ro.Mpp2024.Protocol.Bilet.Parser, new[]{ "Meci", "NumeClient", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protocol.Meci), global::Ro.Mpp2024.Protocol.Meci.Parser, new[]{ "Nume", "NrLocuri", "Pret" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protocol.Persoana), global::Ro.Mpp2024.Protocol.Persoana.Parser, new[]{ "Username", "Parola" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protocol.BasketRequest), global::Ro.Mpp2024.Protocol.BasketRequest.Parser, new[]{ "Type", "Bilet", "Meci", "Persoana" }, new[]{ "Payload" }, new[]{ typeof(global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2024.Protocol.BasketResponse), global::Ro.Mpp2024.Protocol.BasketResponse.Parser, new[]{ "Type", "Error", "Persoana", "Bilet", "Meciuri" }, null, new[]{ typeof(global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protocol.BasketProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      meci_ = other.meci_;
      numeClient_ = other.numeClient_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "meci" field.</summary>
    public const int MeciFieldNumber = 1;
    private int meci_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Meci {
      get { return meci_; }
      set {
        meci_ = value;
      }
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 2;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 3;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Meci != other.Meci) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Meci != 0) hash ^= Meci.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Meci != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Meci);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Meci != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Meci);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Meci != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Meci);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.Meci != 0) {
        Meci = other.Meci;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Meci = input.ReadInt32();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 24: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Meci = input.ReadInt32();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 24: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Meci : pb::IMessage<Meci>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Meci> _parser = new pb::MessageParser<Meci>(() => new Meci());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Meci> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protocol.BasketProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci(Meci other) : this() {
      nume_ = other.nume_;
      nrLocuri_ = other.nrLocuri_;
      pret_ = other.pret_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci Clone() {
      return new Meci(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 2;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    /// <summary>Field number for the "pret" field.</summary>
    public const int PretFieldNumber = 3;
    private float pret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Pret {
      get { return pret_; }
      set {
        pret_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Meci);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Meci other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      if (NrLocuri != other.NrLocuri) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Pret, other.Pret)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (Pret != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Pret);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NrLocuri);
      }
      if (Pret != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Pret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NrLocuri);
      }
      if (Pret != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Pret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (Pret != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Meci other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      if (other.Pret != 0F) {
        Pret = other.Pret;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            NrLocuri = input.ReadInt32();
            break;
          }
          case 29: {
            Pret = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            NrLocuri = input.ReadInt32();
            break;
          }
          case 29: {
            Pret = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Persoana : pb::IMessage<Persoana>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Persoana> _parser = new pb::MessageParser<Persoana>(() => new Persoana());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Persoana> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protocol.BasketProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Persoana() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Persoana(Persoana other) : this() {
      username_ = other.username_;
      parola_ = other.parola_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Persoana Clone() {
      return new Persoana(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 2;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Persoana);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Persoana other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Parola != other.Parola) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Persoana other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BasketRequest : pb::IMessage<BasketRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BasketRequest> _parser = new pb::MessageParser<BasketRequest>(() => new BasketRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BasketRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protocol.BasketProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketRequest(BasketRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Bilet:
          Bilet = other.Bilet.Clone();
          break;
        case PayloadOneofCase.Meci:
          Meci = other.Meci.Clone();
          break;
        case PayloadOneofCase.Persoana:
          Persoana = other.Persoana.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketRequest Clone() {
      return new BasketRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type type_ = global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.Bilet Bilet {
      get { return payloadCase_ == PayloadOneofCase.Bilet ? (global::Ro.Mpp2024.Protocol.Bilet) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Bilet;
      }
    }

    /// <summary>Field number for the "meci" field.</summary>
    public const int MeciFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.Meci Meci {
      get { return payloadCase_ == PayloadOneofCase.Meci ? (global::Ro.Mpp2024.Protocol.Meci) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Meci;
      }
    }

    /// <summary>Field number for the "persoana" field.</summary>
    public const int PersoanaFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.Persoana Persoana {
      get { return payloadCase_ == PayloadOneofCase.Persoana ? (global::Ro.Mpp2024.Protocol.Persoana) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Persoana;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Bilet = 2,
      Meci = 3,
      Persoana = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BasketRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BasketRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (!object.Equals(Meci, other.Meci)) return false;
      if (!object.Equals(Persoana, other.Persoana)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Bilet) hash ^= Bilet.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Meci) hash ^= Meci.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Persoana) hash ^= Persoana.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(18);
        output.WriteMessage(Bilet);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        output.WriteRawTag(26);
        output.WriteMessage(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Persoana) {
        output.WriteRawTag(34);
        output.WriteMessage(Persoana);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(18);
        output.WriteMessage(Bilet);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        output.WriteRawTag(26);
        output.WriteMessage(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Persoana) {
        output.WriteRawTag(34);
        output.WriteMessage(Persoana);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Persoana) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Persoana);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BasketRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Bilet:
          if (Bilet == null) {
            Bilet = new global::Ro.Mpp2024.Protocol.Bilet();
          }
          Bilet.MergeFrom(other.Bilet);
          break;
        case PayloadOneofCase.Meci:
          if (Meci == null) {
            Meci = new global::Ro.Mpp2024.Protocol.Meci();
          }
          Meci.MergeFrom(other.Meci);
          break;
        case PayloadOneofCase.Persoana:
          if (Persoana == null) {
            Persoana = new global::Ro.Mpp2024.Protocol.Persoana();
          }
          Persoana.MergeFrom(other.Persoana);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2024.Protocol.Bilet subBuilder = new global::Ro.Mpp2024.Protocol.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
          case 26: {
            global::Ro.Mpp2024.Protocol.Meci subBuilder = new global::Ro.Mpp2024.Protocol.Meci();
            if (payloadCase_ == PayloadOneofCase.Meci) {
              subBuilder.MergeFrom(Meci);
            }
            input.ReadMessage(subBuilder);
            Meci = subBuilder;
            break;
          }
          case 34: {
            global::Ro.Mpp2024.Protocol.Persoana subBuilder = new global::Ro.Mpp2024.Protocol.Persoana();
            if (payloadCase_ == PayloadOneofCase.Persoana) {
              subBuilder.MergeFrom(Persoana);
            }
            input.ReadMessage(subBuilder);
            Persoana = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protocol.BasketRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2024.Protocol.Bilet subBuilder = new global::Ro.Mpp2024.Protocol.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
          case 26: {
            global::Ro.Mpp2024.Protocol.Meci subBuilder = new global::Ro.Mpp2024.Protocol.Meci();
            if (payloadCase_ == PayloadOneofCase.Meci) {
              subBuilder.MergeFrom(Meci);
            }
            input.ReadMessage(subBuilder);
            Meci = subBuilder;
            break;
          }
          case 34: {
            global::Ro.Mpp2024.Protocol.Persoana subBuilder = new global::Ro.Mpp2024.Protocol.Persoana();
            if (payloadCase_ == PayloadOneofCase.Persoana) {
              subBuilder.MergeFrom(Persoana);
            }
            input.ReadMessage(subBuilder);
            Persoana = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BasketRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("VindeBilet")] VindeBilet = 3,
        [pbr::OriginalName("GetAll")] GetAll = 4,
        [pbr::OriginalName("GetDisponibile")] GetDisponibile = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BasketResponse : pb::IMessage<BasketResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BasketResponse> _parser = new pb::MessageParser<BasketResponse>(() => new BasketResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BasketResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2024.Protocol.BasketProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketResponse(BasketResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      persoana_ = other.persoana_ != null ? other.persoana_.Clone() : null;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      meciuri_ = other.meciuri_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BasketResponse Clone() {
      return new BasketResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type type_ = global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "persoana" field.</summary>
    public const int PersoanaFieldNumber = 3;
    private global::Ro.Mpp2024.Protocol.Persoana persoana_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.Persoana Persoana {
      get { return persoana_; }
      set {
        persoana_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 4;
    private global::Ro.Mpp2024.Protocol.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2024.Protocol.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "meciuri" field.</summary>
    public const int MeciuriFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ro.Mpp2024.Protocol.Meci> _repeated_meciuri_codec
        = pb::FieldCodec.ForMessage(42, global::Ro.Mpp2024.Protocol.Meci.Parser);
    private readonly pbc::RepeatedField<global::Ro.Mpp2024.Protocol.Meci> meciuri_ = new pbc::RepeatedField<global::Ro.Mpp2024.Protocol.Meci>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ro.Mpp2024.Protocol.Meci> Meciuri {
      get { return meciuri_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BasketResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BasketResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Persoana, other.Persoana)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if(!meciuri_.Equals(other.meciuri_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (persoana_ != null) hash ^= Persoana.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      hash ^= meciuri_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (persoana_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Persoana);
      }
      if (bilet_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      meciuri_.WriteTo(output, _repeated_meciuri_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (persoana_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Persoana);
      }
      if (bilet_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      meciuri_.WriteTo(ref output, _repeated_meciuri_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (persoana_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Persoana);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      size += meciuri_.CalculateSize(_repeated_meciuri_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BasketResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.persoana_ != null) {
        if (persoana_ == null) {
          Persoana = new global::Ro.Mpp2024.Protocol.Persoana();
        }
        Persoana.MergeFrom(other.Persoana);
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Ro.Mpp2024.Protocol.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      meciuri_.Add(other.meciuri_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (persoana_ == null) {
              Persoana = new global::Ro.Mpp2024.Protocol.Persoana();
            }
            input.ReadMessage(Persoana);
            break;
          }
          case 34: {
            if (bilet_ == null) {
              Bilet = new global::Ro.Mpp2024.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 42: {
            meciuri_.AddEntriesFrom(input, _repeated_meciuri_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2024.Protocol.BasketResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (persoana_ == null) {
              Persoana = new global::Ro.Mpp2024.Protocol.Persoana();
            }
            input.ReadMessage(Persoana);
            break;
          }
          case 34: {
            if (bilet_ == null) {
              Bilet = new global::Ro.Mpp2024.Protocol.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 42: {
            meciuri_.AddEntriesFrom(ref input, _repeated_meciuri_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the BasketResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("Loggedin")] Loggedin = 3,
        [pbr::OriginalName("Loggedout")] Loggedout = 4,
        [pbr::OriginalName("BiletVandut")] BiletVandut = 5,
        [pbr::OriginalName("GetAll")] GetAll = 6,
        [pbr::OriginalName("GetDisponibile")] GetDisponibile = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
